version: "3.8"
services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./config/dev.env
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: ./config/dev.env
    ports:
      - 3000:3000
    environment:
      - DATABASE=cities
      - PORT=3000
    stdin_open: true
    tty: true
volumes:
  db: