version: "3"
services:
  mongodb:
    image: mongo:5.0.2
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
  app:
    links:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    env_file: ./config/dev.env
    ports:
      - "3000:3000"
    environment:
      - DATABASE=cities
      - PORT=3000

volumes:
  db:
    driver: local